# Message participating in Nao face detection module.
# Contains details about the mouth place in the face detection

std_msgs/Float32 leftLimit_x
std_msgs/Float32 leftLimit_y
std_msgs/Float32 rightLimit_x
std_msgs/Float32 rightLimit_y
std_msgs/Float32 topLimit_x
std_msgs/Float32 topLimit_y
std_msgs/Float32 bottomLimit_x
std_msgs/Float32 bottomLimit_y
std_msgs/Float32 midTopLeftLimit_x
std_msgs/Float32 midTopLeftLimit_y
std_msgs/Float32 midTopRightLimit_x
std_msgs/Float32 midTopRightLimit_y
std_msgs/Float32 midBottomRightLimit_x
std_msgs/Float32 midBottomRightLimit_y
std_msgs/Float32 midBottomLeftLimit_x
std_msgs/Float32 midBottomLeftLimit_y
