# Message participating in Nao face detection module.
# Contains details about the place of the eyes in the detected face

std_msgs/Float32 eyeCenter_x
std_msgs/Float32 eyeCenter_y
std_msgs/Float32 noseSideLimit_x
std_msgs/Float32 noseSideLimit_y
std_msgs/Float32 earSideLimit_x
std_msgs/Float32 earSideLimit_y
std_msgs/Float32 topLimit_x
std_msgs/Float32 topLimit_y
std_msgs/Float32 bottomLimit_x
std_msgs/Float32 bottomLimit_y
std_msgs/Float32 midTopEarLimit_x
std_msgs/Float32 midTopEarLimit_y
std_msgs/Float32 midTopNoseLimit_x
std_msgs/Float32 midTopNoseLimit_y
